---
title: "Practice 7.4"
author: "Yi-Hsuan Lo"
date: "2022-11-22"
output: html_document
---

### Load dataset "rairuoho" 
```{r setup, warning=F, message=F}
data <- read.table("https://www.dipintothereef.com/uploads/3/7/3/5/37359245/rairuoho.txt",header=T)
```

### Extract treatments data -- "nutrient" & "water" 
```{r, warning=F, message=F}
nutrient <- data[which(data$treatment=="nutrient"),1:6]
water <- data[which(data$treatment=="water"),1:6]

nutrient
water
```

### Create my.t.test function
```{r, warning=F, message=F}
my.t.test <- function(x,y,tail){
  
  #mean
  x.mean = apply(x,2,mean)
  y.mean = apply(y,2,mean)
  
  #standard deviation
  x.sd = apply(x,2,sd)
  y.sd = apply(y,2,sd)
  
  #sample size
  x.N = nrow(x)
  y.N = nrow(y)
  
  #t value
  t = (x.mean-y.mean)/sqrt(x.sd^2/x.N+y.sd^2/y.N)
  
  #degree of freedom
  df = nrow(x)+nrow(y)-2
  
  #alternative hypothesis & p value
  if(tail == "two.tailed"){
    p = 2*(1-pt(abs(t),df))
  }else if(tail == "left.tailed"){
    p = pt(t,df)
  }else if(tail == "right.tailed"){
    p = 1-pt(t,df)
  }
  
  return(data.frame(t=round(t,5),p.value=round(p,7),reject=round(p,7)<=0.05))
}
```

### Test
```{r, warning=F, message=F}
my.t.test(nutrient,water,"two.tailed")
```

#### According to the result of data frame above, we reject the null hypothesis at day 7 and day 8 (I assume significant level to be 0.05). Therefore, there is a significant difference in treatment effect at day 7 and day 8.


