---
title: "Ecological data analysis in R Practice 2.2"
author: "Yi-Hsuan Lo"
date: "2022-09-29"
output: html_document
---

#### **Path setting**
```{r setup, warning=FALSE, message=FALSE}
setwd("C:\\Users\\user\\Desktop\\Hsuan\\Courses\\111-1\\Ecological data analysis in R\\Beginner-of-R\\week3_4")
```



#### **Check for packages**
```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
```



#### **Read table from website**
```{r, warning=FALSE, message=FALSE}
rairuoho <- read.table("https://www.dipintothereef.com/uploads/3/7/3/5/37359245/rairuoho.txt",header=T)
head(rairuoho)
```



#### **Replace "nutrient" with "enriched"**
```{r, warning=FALSE, message=FALSE}
rairuoho$treatment <- ifelse(rairuoho$treatment=="nutrient","enriched","water")
head(rairuoho)
```



#### **dplyr pivot_longer**

***Reformat data into longer table***
```{r, warning=FALSE, message=FALSE}
rairuoho_long <- rairuoho %>% pivot_longer(day3:day8,names_to="day",values_to="length")
head(rairuoho_long)
```



#### **dplyr unite**
  
***Combine multiple columns into a single column***
```{r, warning=FALSE, message=FALSE}
rairuoho_long_u <- unite(rairuoho_long,"spatial",spatial1:spatial2,remove=T)
head(rairuoho_long_u)
```


#### **Remove varibles**
```{r, warning=FALSE, message=FALSE}
rairuoho_long_u[,c("row","column")] <- NULL
head(rairuoho_long_u)
```

