---
title: "Ecological analysis in R Practice 3.2"
author: "Yi-Hsuan Lo"
date: "2022-10-04"
output: html_document
---

#### **Load package**
```{r setup, warning=F, message=F}
library("tidyverse")
```



#### **Create initial data frame**
```{r, warning=F, message=F}
before_diet <- c(104,95,87,77,112)
after_diet <- c(96,91,81,75,118)
diet <- data.frame(before_diet,after_diet)
rownames(diet) <- paste("subject_",c(1:5),sep="")
head(diet)
```



#### **Reformat data frame "diet"**
```{r, warning=F, message=F}
diet_r <- diet %>% 
  pivot_longer(before_diet:after_diet, names_to="time", values_to="weight") %>%
  as.data.frame()
diet_r$time <- as.factor(diet_r$time)
str(diet_r)
```



#### **Create "WEIGHT_LOSS" list**
```{r, warning=F, message=F}
subject <- rownames(diet)
weight_loss <- c((diet[,2]-diet[,1])/diet[,1]*100)
w_data <- data.frame(subject,weight_loss)
WEIGHT_LOSS <- list(subject=subject,weight_loss=weight_loss,w_data=w_data)
str(WEIGHT_LOSS)
```



#### **Message**
```{r, warning=F, message=F}
text <- "It's challenging but interesting. I wish I could feel the same when manipulating complicated data."
```



#### **Create "BUBBLE_DIET" list**
```{r, warning=F, message=F}
BUBBLE_DIET <- list(diet_r=diet_r,WEIGHT_LOSS=WEIGHT_LOSS,message=text)
str(BUBBLE_DIET)
BUBBLE_DIET
```



